FloatLayout:
    #A floated layout is what makes it possible for our boxlayouts to be in the center, otherwise.
    #they would on the bottom left corner of the screen, functional but undeniably bad looking.
    canvas.before:
        #A canvas.before is a canvas that is drawn before all the other canvases, useful for backgrounds.
        Rectangle:
            source:'Nutri-gauge Build 8.1/images/app_bg.png'
            #Setting the size of something to root is what makes it possible for the entire
            #background to take up the entire size of the screen.
            size: root.width, root.height

    
    orientation: "vertical"
    Image:
        source: "Nutri-gauge Build 8.1/images/blue_nutri_logo.png"   # <-- Update this path to your actual logo file
        size_hint_y: None
        pos_hint: {"right": 1, "top": 1}
        height: 200
        allow_stretch: True
        keep_ratio: True
    MainScreenManager:
        id: screen_manager

    # Persistent navigation bar at the bottom
    BoxLayout:
        id: nav_bar
        size_hint_y: None
        height: "50dp"
        spacing: 5
        opacity: 1 if screen_manager.current != "login" else 0
        disabled: True if screen_manager.current == "login" else False
        ButtonNavbar:
            text: ""
            on_press: screen_manager.current = "goal"
            Image:
                source: "Nutri-gauge Build 8.1\images\Goals.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        ButtonNavbar:
            text: ""
            on_press: screen_manager.current = "food_log_screen"
            Image:
                source: "Nutri-gauge Build 8.1\images\Food_log.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        ButtonNavbar:
            text: ""
            on_press: screen_manager.current = "generate_screen"
            Image:
                source: "Nutri-gauge Build 8.1\images\Generate.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        ButtonNavbar:
            text: ""
            on_press: screen_manager.current = "daily_intake_screen"
            Image:
                source: "Nutri-gauge Build 8.1\images\Daily_intake.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        ButtonNavbar:
            text: ""
            on_press: screen_manager.current = "progress_screen"
            Image:
                source: "Nutri-gauge Build 8.1\images\Progress_bar.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y

<MainScreenManager>:
    LoginScreen:
        name: "login"
    GoalScreen:
        name: "goal"
    NewScreen:
        name: "food_log_screen"
    DailyIntakeScreenWrapper:
        name: "daily_intake_screen"
    ProgressScreenWrapper:
        name: "progress_screen"
    GenerateScreenWrapper:
        name: "generate_screen"

<GoalScreen>:
    NutritionInputScreen:

<NewScreen>:
    FoodLogScreen:

<DailyIntakeScreenWrapper>:
    DailyIntakeScreen:

<ProgressScreenWrapper>:
    ProgressScreen:

<GenerateScreenWrapper>:
    GenerateScreen:

#Our nutrition goals input screen.
<NutritionInputScreen>:
    #Take over the entire width of the app but only 90% of the height.
    size_hint: 1, 0.9
    #Position yourself at the very top of the app.
    pos_hint: {'top': 1}
    orientation: "vertical"
    background_normal: ""
    padding: 50
    spacing: 10

    #Box layout containing our Text Inputs.
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                #Redish Background
                rgba: (	255/255, 111/255, 97/255, 1)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                #Rounded all corners.
                radius: [20,20,20,20]

        #Keep the TextInputs 20 pixels away from the edges of the screen.
        padding: 20
        #Keep the TextInputs 10 pixels apart.
        spacing: 10
        Label:
            bold: True
            text: "Set Your Nutrition Goals"
        FocusTextInput:
            id: calories_input
            hint_text: "Calories"
            input_filter: 'float'
        FocusTextInput:
            id: protein_input
            hint_text: "Protein (g)"
            input_filter: 'float'
        FocusTextInput:
            id: calcium_input
            hint_text: "Calcium (mg)"
            input_filter: 'float'
        FocusTextInput:
            id: fats_input
            hint_text: "Fats"
            input_filter: 'float'
        FocusTextInput:
            id: trans_fats_input
            hint_text: "Trans Fats"
            input_filter: 'float'
        FocusTextInput:
            id: cholesterol_input
            hint_text: "Cholesterol"
            input_filter: 'float'
        FocusTextInput:
            id: carbohydrates_input
            hint_text: "Carbohydrates"
            input_filter: 'float'
        FocusTextInput:
            id: fiber_input
            hint_text: "Fiber"
            input_filter: 'float'
        FocusTextInput:
            id: iron_input
            hint_text: "Iron"
            input_filter: 'float'
        FocusTextInput:
            id: sodium_input
            hint_text: "Sodium"
            input_filter: 'float'
        FocusTextInput:
            id: total_fats_input
            hint_text: "Total Fats Goal (g)"
            input_filter: "float"
            multiline: False
        FocusTextInput:
            id: saturated_fats_input
            hint_text: "Saturated Fats Goal (g)"
            input_filter: "float"
            multiline: False
        FocusTextInput:
            id: sugar_input
            hint_text: "Sugar Goal (g)"
            input_filter: "float"
            multiline: False
        SaveGoalsRoundedButton:
            text: "Save Goals"
            on_press: root.save_data()


<FoodLogScreen>:
    #Take over the entire width of the app but only 95% of the height.
    size_hint: 1, 0.95
    #Position yourself at the very top of the app.
    pos_hint: {'top': 1}
    orientation: "vertical"
    background_normal: ""
    padding: 50
    spacing: 10

    #Box layout containing our Text Inputs.
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                #Redish Background
                rgba: (	255/255, 111/255, 97/255, 1)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                #Rounded all corners.
                radius: [20,20,20,20]

        #Keep the TextInputs 10 pixels away from the edges of the screen.
        padding: 10
        #Keep the TextInputs 10 pixels apart.
        spacing: 10
        BoxLayout:
            orientation: "vertical"
            spacing: 5
            Label:
                text: "Log a Food Item"
                bold: True
                font_size: 24
            FocusTextInput:
                id: food_name_input
                hint_text: "Food Name"
            FocusTextInput:
                id: food_serving_size_input
                hint_text: "Serving Size"
            FocusTextInput:
                id: food_calories_input
                hint_text: "Calories"
                input_filter: 'float'
            FocusTextInput:
                id: food_protein_input
                hint_text: "Protein"
                input_filter: 'float'
            FocusTextInput:
                id: food_calcium_input
                hint_text: "Calcium"
                input_filter: 'float'
            FocusTextInput:
                id: food_fats_input
                hint_text: "Fats"
                input_filter: 'float'
            FocusTextInput:
                id: food_trans_fats_input
                hint_text: "Trans Fats"
                input_filter: 'float'
            FocusTextInput:
                id: food_cholesterol_input
                hint_text: "Cholesterol"
                input_filter: 'float'
            FocusTextInput:
                id: food_carbohydrates_input
                hint_text: "Carbohydrates"
                input_filter: 'float'
            FocusTextInput:
                id: food_fiber_input
                hint_text: "Fiber"
                input_filter: 'float'
            FocusTextInput:
                id: food_iron_input
                hint_text: "Iron"
                input_filter: 'float'
            FocusTextInput:
                id: food_sodium_input
                hint_text: "Sodium"
                input_filter: 'float'
            FocusTextInput:
                id: food_total_fats_input
                hint_text: "Total Fats (g)"
                input_filter: "float"
                multiline: False
            FocusTextInput:
                id: food_saturated_fats_input
                hint_text: "Saturated Fats (g)"
                input_filter: "float"
                multiline: False
            FocusTextInput:
                id: food_sugar_input
                hint_text: "Sugar (g)"
                input_filter: "float"
                multiline: False
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: "40dp"
            spacing: 8
            LogFoodRoundedButton:
                text: "Log Food"
                size_hint_y: None
                height: 40
                on_press: root.log_food()

            LogFoodRoundedButton:
                text: "Browse Food Database"
                size_hint_y: None
                height: 40
                on_release: root.show_food_database()
        LogFoodRoundedButton:
            text: "Logged Food"
            size_hint_y: None
            height: 40
            on_release: root.show_logged_foods()


<DailyIntakeScreen>:
    #Take over the entire width of the app but only 90% of the height.
    size_hint: 1, 0.9
    #Position yourself at the very top of the app.
    pos_hint: {'top': 1}
    orientation: "vertical"
    background_normal: ""
    padding: 50
    spacing: 10
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: (255/255, 111/255, 97/255, 1)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                radius: [20,20,20,20]

        padding: 20
        spacing: 10

        Label:
            text: "Add Food to Today's Intake"
            bold: True
            size_hint_y: None
            height: "40dp"

        SelectFoodSpinner:
            id: food_spinner
            text: "Select food"
            values: root.food_options
            size_hint_y: None
            height: "40dp"

        Widget:  # Spacer
            size_hint_y: 1

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: "40dp"
            spacing: 5

            RoundedButton:
                text: "Add Food"
                on_press: root.add_consumed_food()
                canvas.before:
                    Color:
                        rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
                    RoundedRectangle: 
                        size: self.size
                        pos: self.pos
                        radius:[20,20,20,20]

            RoundedButton:
                text: "Refresh Foods"
                on_press: root.refresh_food_options()
                canvas.before:
                    Color:
                        rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
                    RoundedRectangle: 
                        size: self.size
                        pos: self.pos
                        radius:[20,20,20,20]

            RoundedButton:
                text: "View Progress"
                on_press: app.root.ids.screen_manager.current = "progress_screen"
                canvas.before:
                    Color:
                        rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
                    RoundedRectangle: 
                        size: self.size
                        pos: self.pos
                        radius:[20,20,20,20]

            RoundedButton:
                text: "Today's Intake"
                on_release: root.show_todays_intake()
                canvas.before:
                    Color:
                        rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
                    RoundedRectangle: 
                        size: self.size
                        pos: self.pos
                        radius:[20,20,20,20]
<ProgressScreen>:
    #Take over the entire width of the app but only 90% of the height.
    size_hint: 1, 0.9
    #Position yourself at the very top of the app.
    pos_hint: {'top': 1}
    orientation: "vertical"
    background_normal: ""
    padding: 50
    spacing: 10

    #Box layout containing our Text Inputs.
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                #Redish Background
                rgba: (	255/255, 111/255, 97/255, 1)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                #Rounded all corners.
                radius: [20,20,20,20]

        #Keep the TextInputs 20 pixels away from the edges of the screen.
        padding: 20
        #Keep the TextInputs 10 pixels apart.
        spacing: 10
        BoxLayout:
            orientation: "vertical"
            spacing: 10
            Label:
                text: "Your Progress"
                bold: True
                size_hint_y: None
                height: "40dp"
            Label:
                text: root.progress_text
                text_size: self.width, None
                size_hint_y: 1
            BoxLayout:
                orientation: "horizontal"
                size_hint_y: None
                height: "40dp"
                spacing: 10
                RoundedButton:
                    text: "Update Progress"
                    on_press: root.update_progress()

<GenerateScreen>:
    #Take over the entire width of the app but only 90% of the height.
    size_hint: 1, 0.9
    #Position yourself at the very top of the app.
    pos_hint: {'top': 1}
    orientation: "vertical"
    background_normal: ""
    padding: 50
    spacing: 10

    #Box layout containing our Text Inputs.
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                #Redish Background
                rgba: (	255/255, 111/255, 97/255, 1)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                #Rounded all corners.
                radius: [20,20,20,20]

        #Keep the TextInputs 20 pixels away from the edges of the screen.
        padding: 20
        #Keep the TextInputs 10 pixels apart.
        spacing: 10
        RoundedButton:
            text: "Generate"
            size_hint_y: None
            height: 50
            on_release: root.generate_meal_plan()

        ScrollView:
            Label:
                id: meal_plan_label
                text: root.meal_plan_text
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

<LoginScreen>:
    size_hint: None, None
    size: 300, 400
    pos_hint: {"center_x": 0.5, "center_y": 0.5}
    orientation: "vertical"
    background_normal: ""
    elevation: 10
    padding: 25
    spacing: 25
    BoxLayout:
        padding: 25
        spacing: 25
        orientation: 'vertical'
        canvas.before:
            Color:
                #Redish Background
                rgba: (	255/255, 111/255, 97/255, 1)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                #Rounded all corners.
                radius: [20,20,20,20]
        Label:
            text: "Welcome to Nutri[color=0097A7]Gauge[/color]"
            font_size: 25
            bold: True
            markup: True
        TextInput:
            id: login_username
            hint_text: "Username"
            spacing_top: 10
            multiline: False
        TextInput:
            id: login_password
            hint_text: "Password"
            spacing_top: 10
            password: True
            multiline: False
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10
            Buttonstuff:
                text: "Log In"
                on_release: root.login()
            Buttonstuff:
                text: "Sign Up"
                on_release: root.signup()

#A rounded button, it is said that all rounded buttons inherit from this one. Indeed, their unique
#roundedness and their colors are inherited from here, Diba Brendan? Tignan mo, kahit si Brendan naniniwala
#sa akin, bakit ikaw hindi?
<RoundedButton@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    canvas.before:
        Color:
            rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
        RoundedRectangle: 
            size: self.size
            pos: self.pos
            radius:[20,20,20,20]

<Buttonstuff@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    canvas.before:
        Color:
            rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos

<LogFoodInput@TextInput>:
    multiline: False
    size_hint_y: None
    height: "27dp"
    spacing: '3dp'

<LogFoodRoundedButton@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    canvas.before:
        Color:
            rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(179/255, 77/255, 67/255, 1)
        RoundedRectangle: 
            size: self.size
            pos: self.pos
            radius:[10,10,10,10]

<SaveGoalsRoundedButton@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    canvas.before:
        Color:
            rgba:(0/255, 151/255, 167/255,1)if self.state == 'normal' else(180/255, 54/255, 0/255, 1)
        RoundedRectangle: 
            size: self.size
            pos: self.pos
            radius:[10,10,10,10]

<ButtonNavbar@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    size_hint: .15, 1
#    size_hint_y: None
#    height: "30dp"
    canvas.before:
        Color:
            rgba: (	255/255, 111/255, 97/255, 1)if self.state == 'normal' else(179/255, 77/255, 67/255, 1)
        Rectangle: 
            size: self.size
            pos: self.pos
<SelectFoodSpinner@Spinner>:
    background_color: (0,0,0,0)
    background_normal: ''
    option_cls: "CustomSpinnerOption"
    canvas.before:
        Color:
            rgba: (0/255, 151/255, 167/255, 1) if self.state == 'normal' else (179/255, 77/255, 67/255, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10, 10, 10, 10]

<CustomSpinnerOption@SpinnerOption>:
    background_color: (0,0,0,0)
    background_normal: ''
    canvas.before:
        Color:
            rgba: (255/255, 111/255, 97/255, 1) if self.state == 'down' else (0/255, 151/255, 167/255, 1)
        Rectangle:
            size: self.size
            pos: self.pos
